export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const LOGOUT_USER = 'LOGOUT_USER'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_TASK_BEGIN = 'CREATE_TASK_BEGIN'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const SET_EDIT_TASK = 'SET_EDIT_TASK'

export const EDIT_TASK_BEGIN = 'EDIT_TASK_BEGIN'
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS'
export const EDIT_TASK_ERROR = 'EDIT_TASK_ERROR'

export const GET_COMPANIES_BEGIN = 'GET_COMPANIES_BEGIN'
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS'

export const GET_EMPLOYEES_BEGIN = 'GET_EMPLOYEES_BEGIN'
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS'

export const GET_TASKS_BEGIN = 'GET_TASKS_BEGIN'
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS'

export const TOGGLE_STATUS_BEGIN = 'TOGGLE_STATUS_BEGIN'
export const TOGGLE_STATUS_SUCCESS = 'TOGGLE_STATUS_SUCCESS'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN'

export const CLEAR_FILTERS = 'CLEAR_FILTERS'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'